<a href="https://colab.research.google.com/github/Seth-Eno/CPTR141-Final-Project/blob/main/Cptr141FinalProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Odds
### CPTR 141 Final Project

Seth Eno

## Introduction
The titanic was a luxury passenger ship built to travel between England and New York. The titantic sank on April 15, 1912. It had 20 lifeboats, enough for about half its passengers. What allowed you to be saved and what doomed you to the icy depths was based on many factors some of which were recorded back in 1912 and included in this data set: https://www.kaggle.com/datasets/yasserh/titanic-dataset

## Dataset
From this dataset I plan to learn what factors most influence survival rates on the titanic. Leanring these factors can give valuable insights on what happened on that fateful night in 1912.

Some examples of these insigts are: the relationships between men and women in 1912, privillege given to those with more money, what was considered a child in 1912 compared to what we consider a child in 2024, and more.

In [ ]:
import pandas as pd
import kagglehub
import os
import csv
import matplotlib.pyplot as plt
import seaborn as sns

path = kagglehub.dataset_download("yasserh/titanic-dataset")
filePath = (f'{path}/Titanic-Dataset.csv')
funct = ''
'''
Write at least ten (10) functions that provide unique analysis of the data (min, max, average, top 10, or similar ideas).
'''

def main():
  data = pd.read_csv(filePath)
  data.fillna('', inplace=True)

  def loop():
     return False
  def welcome():
    print('\n\nWelcome!\n')

  def menu():
    global funct
    print('0. Quit\n1. View Data\n2. How likely were men to survive?\n3. How likely were women to survive?\n4. Class survival rates\n5. Age survival rates\n6. Likelihood to survive if you have relatives on board\n7. Survival rates by deck\n8. Survival by port of embarkment\n9. Intersectional analysis\n10. Simulation')
    funct = input('what would you like to do?')

  def printData():
    display(data)

  def maleSurvivalRate():
    with open(filePath, 'r') as file:
      died = 0
      survived = 0
      total = 0
      reader = csv.DictReader(file)
      for passenger in reader:
        if passenger['Sex'] == 'male':
          total += 1
          if passenger['Survived'] == '0':
            died += 1
          elif passenger['Survived'] == '1':
            survived += 1
      survivalRate = round(((survived/total) * 100), 2)
      print(f'Total Males: {total}\nSurvived: {survived}\nDied: {died}\nSurvival Rate: {survivalRate}%')

  def femaleSurvivalRate():
    with open(filePath, 'r') as file:
      died = 0
      survived = 0
      total = 0
      reader = csv.DictReader(file)
      for passenger in reader:
        if passenger['Sex'] == 'female':
          total += 1
          if passenger['Survived'] == '0':
            died += 1
          elif passenger['Survived'] == '1':
            survived += 1
      survivalRate = round(((survived/total) * 100), 2)
      print(f'Total Females: {total}\nSurvived: {survived}\nDied: {died}\nSurvival Rate: {survivalRate}%')

  def classSurvivalRates():
    with open(filePath, 'r') as file:
      firstClassDied = 0
      firstClassSurvived = 0
      firstClassTotal = 0
      secondClassDied = 0
      secondClassSurvived = 0
      secondClassTotal = 0
      thirdClassDied = 0
      thirdClassSurvived = 0
      thirdClassTotal = 0
      missingClass = 0
      reader = csv.DictReader(file)
      for passenger in reader:
        if passenger['Pclass'] == '1':
          firstClassTotal += 1
          if passenger['Survived'] == '0':
             firstClassDied += 1
          elif passenger['Survived'] == '1':
            firstClassSurvived += 1
        elif passenger['Pclass'] == '2':
          secondClassTotal += 1
          if passenger['Survived'] == '0':
            secondClassDied += 1
          elif passenger['Survived'] == '1':
            secondClassSurvived += 1
        else:
          thirdClassTotal += 1
          if passenger['Survived'] == '0':
             thirdClassDied += 1
          elif passenger['Survived'] == '1':
            thirdClassSurvived += 1
      firstClassSurvivalRate = round(((firstClassSurvived/firstClassTotal) * 100), 2)
      secondClassSurvivalRate = round(((secondClassSurvived/secondClassTotal) * 100), 2)
      thirdClassSurvivalRate = round(((thirdClassSurvived/thirdClassTotal) * 100), 2)
      print(f'First class survival rate: {firstClassSurvivalRate}%\nSecond class survival rate: {secondClassSurvivalRate}%\nThird class survival rate: {thirdClassSurvivalRate}%')

  def survivalRatesByAge(data):
    data['Age'] = pd.to_numeric(data['Age'])
    data['Survived'] = pd.to_numeric(data['Survived'])
    data = data.dropna(subset=['Age'])

    bins = list(range(0, 64 + 3, 3))
    labels = [f"{age}-{age+1}" for age in range(0, 64, 3)]
    data['Age Group'] = pd.cut(data['Age'], bins=bins, labels=labels, right=False)

    survival_rates = data.groupby('Age Group')['Survived'].mean() * 100

    plt.figure(figsize=(8, 6))
    survival_rates.plot(kind='bar', width=0.8)
    plt.title('Survival Rates By Age', fontsize=16)
    plt.xlabel('Age Group', fontsize=14)
    plt.ylabel('Survival Rate %', fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

  def survivalWithRelatives(data):
    with open(filePath, 'r') as file:
      reader = csv.DictReader(file)
      survivedWRelatives = 0
      survivedWORelatives = 0
      totalWRelatives = 0
      totalWORelatives = 0
      for passenger in reader:
        if (int(passenger['SibSp']) > 0 or int(passenger['Parch']) > 0):
          totalWRelatives += 1
          if passenger['Survived'] == '1':
            survivedWRelatives += 1
        elif (int(passenger['SibSp']) < 1 or int(passenger['Parch']) < 1):
          totalWORelatives += 1
          if passenger['Survived'] == '1':
            survivedWORelatives += 1
      ratioWORelatives = round(((survivedWORelatives/(totalWORelatives)) * 100), 2)
      ratioWRelatives = round(((survivedWRelatives/(totalWRelatives)) * 100), 2)
      print(f'Survival rate with relatives: {ratioWRelatives}%\nSurvival rate without relatives: {ratioWORelatives}%')

  def survivalRatesByDeck(data):
    data['Cabin'].replace('', pd.NA, inplace=True)
    data['Survived'] = pd.to_numeric(data['Survived'])
    noCabin = data[data['Cabin'].isna()]
    noCabinSurvivalRate = round((noCabin['Survived'].mean() * 100), 2)
    data = data.dropna(subset=['Cabin'])
    data['Deck'] = data['Cabin'].str[0]

    survival_rates = data.groupby('Deck')['Survived'].mean() * 100

    plt.figure(figsize=(8, 6))
    survival_rates.plot(kind='bar', width=0.8)
    plt.title('Survival Rates By Deck', fontsize=16)
    plt.xlabel('Deck', fontsize=14)
    plt.ylabel('Survival Rate %', fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.axhline(y=noCabinSurvivalRate, color='red', linestyle='--', linewidth=2, label=f'Missing Cabin: {noCabinSurvivalRate:.2f}%')
    plt.tight_layout()
    plt.show()
    print(f'DISCLAIMER: data is biased toward survival because living passengers could report their cabin, many deceased passengers cabins were unknown and not included in this analysis.\nThere were {len(noCabin)} passengers in unknown cabins with a survival rate of {noCabinSurvivalRate}%. The dotted red line indicates the survival rate of those without a known cabin assignment.')

  def survivalByPortOfEmbarkment():
    survivedS = 0
    survivedC = 0
    survivedQ = 0
    totalS = 0
    totalC = 0
    totalQ = 0
    with open(filePath, 'r') as file:
      reader = csv.DictReader(file)
      for passenger in reader:
        if passenger['Embarked'] == 'S':
          totalS += 1
          if passenger['Survived'] == '1':
            survivedS += 1
        if passenger['Embarked'] == 'C':
          totalC += 1
          if passenger['Survived'] == '1':
            survivedC += 1
        if passenger['Embarked'] == 'Q':
          totalQ += 1
          if passenger['Survived'] == '1':
            survivedQ += 1
      survivalRateS = round(((survivedS/totalS) * 100), 2)
      survialRateQ = round(((survivedQ/totalQ) * 100), 2)
      survivalRateC = round(((survivedC/totalC) * 100), 2)
      print(f'Surival rates by where each passenger embarked the tianic\nSouthampton: {survivalRateS}%\nCherbourg: {survivalRateC}%\nQueenstown: {survialRateQ}%')

  def intersectionalAnalysis(data):
    data['Age'] = pd.to_numeric(data['Age'])
    data['Survived'] = pd.to_numeric(data['Survived'])
    data = data.dropna(subset=['Age'])
    data = data.dropna(subset=['Embarked'])
    originalData = data.copy()

    data = data[data['Sex'] == 'female']

    femaleSurvivalRates = data.groupby('Pclass')['Survived'].mean() * 100

    data = originalData.copy()
    data = data[data['Sex'] == 'male']

    maleSurvivalRates = data.groupby('Pclass')['Survived'].mean() * 100

    survival_rates = pd.DataFrame({
    'Women': femaleSurvivalRates,
    'Men': maleSurvivalRates
    })

    plt.figure(figsize=(8, 6))
    survival_rates.plot(kind='bar', width=0.5)
    plt.title('Survival Rates By Class And Sex', fontsize=16)
    plt.xlabel('Class', fontsize=14)
    plt.ylabel('Survival Rate %', fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    data = originalData.copy()

    data['AgeGroup'] = pd.cut(data['Age'], bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90], labels= ['(0-10)', '(10-20)', '(20-30)', '(30-40)', '(40-50)', '(50-60)', '(60-70)', '(70-80)', '(80-90)'])
    labels = ['1st class females', '1st class males', '2nd class females', '2nd class males', '3rd class females', '3rd class males']

    heatmap_data = data.pivot_table(
    values='Survived',
    index='AgeGroup',
    columns=['Pclass', 'Sex'],
    aggfunc='mean'
    ) * 100
    print('\n\n')
    # Plot the heatmap
    plt.figure(figsize=(12, 8))
    sns.heatmap(heatmap_data, annot=True, fmt=".1f", cmap="coolwarm", cbar_kws={'label': 'Survival Rate (%)'})
    plt.title('Survival Rates by Age, Class, and Gender', fontsize=16)
    plt.xlabel('Class and Gender', fontsize=14)
    plt.ylabel('Age Group', fontsize=14)
    plt.xticks(ticks=[i + 0.5 for i in range(len(labels))], labels=labels, rotation=45, ha='center')
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    print('\n\n')

    data = originalData.copy()
    data = data[data['Embarked'].isin(['Q', 'S', 'C'])]
    labels = ['Southampton', 'Cherbourg', 'Qeensland']

    citySurvivalRates = data.groupby('Embarked')['Survived'].mean() * 100
    color = [(0, 0.3, 0), (0, 0.6, 0), (0, 1, 0)]


    plt.figure(figsize=(8, 6))
    citySurvivalRates.plot(kind='bar', width=0.5, color = color)
    plt.title('Survival Rates By City Wealth\n(Darker = Wealthier City)', fontsize=16,)
    plt.xlabel('City', fontsize=14)
    plt.xticks(ticks=range(len(labels)), labels=labels, fontsize=12, rotation = 0)
    plt.ylabel('Survival Rate %', fontsize=14)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

  def simulation(data):
    age = (input('What is your age?'))
    income = (input('How much do you make in a month?'))
    pClass = 0
    sex = input('What is your sex? (male or female)')
    if not age.isdigit() or not income.isdigit():
        print("Invalid input: Age and income must be integers.")
        return

    if sex not in ['male', 'female']:
        print("Invalid input for sex. Please enter 'male' or 'female'.")
        return
    age = int(age)
    income = int(income)
    pClass = 3 if income < 1071 else 2 if income < 1834 else 1
    data = data[(pd.to_numeric(data['Age']) > age - 5) & (pd.to_numeric(data['Age']) < age + 5)]
    if not data[data['Sex'] == sex].empty:
      data = data[data['Sex'] == sex.lower()]
    if not data[data['Pclass'] == pClass].empty:
      data = data[data['Pclass'] == pClass]


    if not data.empty:
        totalPassengers = len(data)
        totalSurvivors = pd.to_numeric(data['Survived']).sum()
        survivalRate = round((((totalSurvivors / totalPassengers) * 100)), 2)
        print(f"Based on passengers like you: you have a {survivalRate}% chance of surviving!")
    else:
       print("No passengers are like you.")



  welcome()
  menu()

  if funct == '0':
    loop()
  elif funct == '1':
    printData()
    loop()
  elif funct == '2':
    maleSurvivalRate()
    loop()
  elif funct == '3':
    femaleSurvivalRate()
    loop()
  elif funct == '4':
    classSurvivalRates()
    loop()
  elif funct == '5':
    survivalRatesByAge(data)
    loop()
  elif funct == '6':
    survivalWithRelatives(data)
    loop()
  elif funct == '7':
    survivalRatesByDeck(data)
    loop()
  elif funct == '8':
    survivalByPortOfEmbarkment()
    loop()
  elif funct == '9':
    intersectionalAnalysis(data)
    loop()
  elif funct == '10':
    simulation(data)
    loop()
  else:
    print('Please input a valid option!')

9
if __name__ == "__main__":
    main()

<ipython-input-10-5249f8c536ca>:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.fillna('', inplace=True)

Welcome!

0. Quit
1. View Data
2. How likely were men to survive?
3. How likely were women to survive?
4. Class survival rates
5. Age survival rates
6. Likelihood to survive if you have relatives on board
7. Survival rates by deck
8. Survival by port of embarkment
9. Intersectional analysis
10. Simulation
what would you like to do?1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,,1,2,W./C. 6607,23.4500,,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,,Q

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
y

# Conclusion
Using this analysis I have discovered the most affluential factors that predict survival rates on the titanic were age, sex, and class. The most helpful model for visualizing this is the multivariable analysis with a heatmap relating age, class, and gender to survival rates. The trend is clear: if you want to survive the sinking of the titanic, be a first or second class woman or be under 10 years old. This data indicates a few cultural shifts between 1912 and now. Nowadays, women are given more equallity and probably would have a lower survival rate if the titanic were to sink today. In 1912, children were considered to be about 12 and under, today someone is a child until they are 18. Something that hasn't changed between 1912 and 2024 is the privillege wealthy people get.

# Reflection
During this project I used Matplotlib for the first time. I struggled with it quite a bit. The syntax is quite tricky. At first I made many scematic errors because I got confused the difference between x and y ticks and x and y labels. Creating the dataframe to build the heat map took me a long time to figure out. I foresee myself using python extensively in the future for mathematical computations because it has an excellent library ecosystem and it's relatively simple. Because of it's usability in computations, it is the major language for machine learning. I think I will use python extensively in my future for ML.